$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    responsive:{
        0:{
            items:1
        },
        400:{
            items:3
        },
        600:{
            items:6
        },
        750:{
            items:8
        },
        1000:{
            items:10
        }
    }
})